Lmoran fix/hibernate5 upgrade
uPortal-Project/SimpleContentPortlet pull request #460
Opened 2023-08-01 20:58 UTC by loulou2u

Resolving hibernate 5 related errors that were introduced in the last version upgrade.

2023-08-01 21:06 UTC, ChristianMurphy approved these changes

2023-08-01 21:06 UTC, ChristianMurphy commented on pom.xml
> -                <version>${hibernate-jpamodelgen.version}</version>
Is this variable still floating around in a config?
Can we remove it?

2023-08-01 21:06 UTC, ChristianMurphy commented on src/main/resources/context/baseContext.xml
> +
does this empty line need to be indented?
```suggestion

```

2023-08-01 21:06 UTC, ChristianMurphy commented on src/main/java/org/jasig/portlet/attachment/util/SchemaCreator.java
> +import org.hibernate.boot.registry.StandardServiceRegistryBuilder;
These imports look the same as the ones which were removed above?
Was this done to better match a style guide? Is there a subtle ordering problem? or something else?

2023-08-01 21:12 UTC, loulou2u commented on src/main/java/org/jasig/portlet/attachment/util/SchemaCreator.java
> +import org.hibernate.boot.registry.StandardServiceRegistryBuilder;
It was a case of reverting the changes and then re-adding the new additions to the bottom. Nothing significant :)

2023-08-01 21:21 UTC, loulou2u commented on pom.xml
> -                <version>${hibernate-jpamodelgen.version}</version>
Yes, it had been removed and replaced with the hibernate.version variable

2023-08-01 21:25 UTC, ChristianMurphy approved these changes

2023-08-07 17:22 UTC, cbeach47 requested changes
Thanks @loulou2u ! 

Besides the inline comments, the Hibernate migration guides talks about issues with the `@Lob` annotation which we use in Attachment.java , and PostgreSQL. Do we need to make any code or documentation changes?

2023-08-07 17:22 UTC, cbeach47 commented on src/main/java/org/jasig/portlet/attachment/util/SchemaCreator.java
> +            settings.put("hibernate.dialect",hibernateDialect);
In a different branch that I'll revert, I needed to add in the following. Is there any merit to specifying these settings?

```
    @Value("${hibernate.dialect}")
    private String hibernateDialect;

    @Value("${hibernate.connection.driver_class}")
    private String hibernateDriverClass;

    @Value("${hibernate.connection.url}")
    private String hibernateConnectionUrl;

    @Value("${hibernate.connection.username}")
    private String hibernateConnectionUsername;

    @Value("${hibernate.connection.password}")
    private String hibernateConnectionPassword;

    @Value("${hibernate.connection.validationQuery}")
    private String hibernateConnectionValidationQuery;
...
            settings.put("hibernate.connection.driver_class", hibernateDriverClass);
            settings.put("hibernate.dialect", hibernateDialect);
            settings.put("hibernate.connection.url", hibernateConnectionUrl);
            settings.put("hibernate.connection.username", hibernateConnectionUsername);
            settings.put("hibernate.connection.password", hibernateConnectionPassword);
            settings.put("hibernate.connection.validationQuery", hibernateConnectionValidationQuery);
```

2023-08-15 15:21 UTC, bjagg approved these changes
Looks great!!

2023-08-15 15:21 UTC, bjagg commented on src/main/java/org/jasig/portlet/attachment/util/SchemaCreator.java
Wish Lombok was a dependency to handle log creation.

2023-08-15 15:21 UTC, bjagg commented on src/main/java/org/jasig/portlet/attachment/util/SchemaCreator.java
> +            MetadataSources metadata = new MetadataSources(serviceRegistry.getParentServiceRegistry());
Glad this works!

2023-08-15 15:21 UTC, bjagg commented on src/main/java/org/jasig/portlet/attachment/util/SchemaCreator.java
>                  }
This could be rewritten to:
```
exceptions.forEach(e -> logger.error("Exception from Hibernate Tools SchemaExport", e));
```
or 
```
exceptions.forEach(e -> 
    logger.error("Exception from Hibernate Tools SchemaExport", e)
);
```
This stated, we are not on a quest to eradicate all external iteration. We can keep this since it's clean and clear.

2023-08-16 13:29 UTC, groybal commented on src/main/java/org/jasig/portlet/attachment/util/SchemaCreator.java
> +            settings.put("hibernate.dialect",hibernateDialect);
My original fix used these same @Value setting, but I found a way to not need them so they were removed.

2023-08-16 13:39 UTC, groybal commented on pom.xml
>          <hibernate-jpa-api.version>1.0.0.Final</hibernate-jpa-api.version>
No longer needed, as it's been deprecated (see:  https://github.com/hibernate/hibernate-jpa-api).  Was replaced with:
```
            <dependency>
                <groupId>javax.persistence</groupId>
                <artifactId>javax.persistence-api</artifactId>
                <version>${persistence-api.version}</version>
            </dependency>
```

2023-08-16 16:41 UTC, merged