UPSE-394: Update to use Spring Data JPA
uPortal-Project/SimpleContentPortlet pull request #467
Opened 2023-08-27 20:24 UTC by groybal

See:

- https://jira.unicon.net/jira/browse/UPSE-394

Notes:

- I used version 2.7.15 of  Spring Data JPA because more recent versions require Java 17
- I removed batch/paging option for 'get all' because that can be configured with hibernate properties

2023-08-28 10:30 UTC, cbeach47 requested changes
Looking good! A clean up comment in the service layer.

2023-08-28 10:30 UTC, cbeach47 commented on src/main/java/org/jasig/portlet/attachment/service/impl/AttachmentService.java
> +        return attachmentsRepository;
Is this and the related setter used? Since the attachmentRepository is Autowired, I'm thinking we can remove these two methods.

2023-08-29 15:24 UTC, groybal commented on src/main/java/org/jasig/portlet/attachment/service/impl/AttachmentService.java
> +        return attachmentsRepository;
done

2023-08-31 16:43 UTC, cbeach47 approved these changes

2023-08-31 16:59 UTC, merged